# Generated by Django 5.1.4 on 2024-12-16 12:32

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(validators=[accounts.validators.validate_published_date]),
        ),
    ]
